// apps/web/src/routes/call/VideoGrid.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import type { CallContext } from "./createCallState.svelte";
    import Video from "./Video.svelte";
    import LocalVideo from "./LocalVideo.svelte";

    const callContext = getContext<CallContext>("call");
</script>

<div class="p-4 pb-0" style="height: calc(100% - 80px)">
    <div class="h-full grid grid-cols-4 gap-4">
        <LocalVideo />
        {#each Object.keys(callContext.peerConnection.peers) as peer}
            <Video peerId={peer} />
        {/each}
    </div>
</div>

// apps/web-react/app/components/Video/VideoGrid.tsx
import { usePeers } from "../../store/peersContext";
import { RemoteVideo } from "./RemoteVideo";
import { LocalVideo } from "./LocalVideo";

export const VideoGrid = () => {
    const { peers } = usePeers();
    return (
        <>
            {/* <Grid columns="2" gap="3" rows="2" width="100vw" height="100vh" p="4">
                <Box>
                    <LocalVideo />
                </Box>
                {Object.keys(peers).map((p) => (
                    <Box key={peers[p].peerId}>
                        <RemoteVideo peerId={peers[p].peerId} />
                    </Box>
                ))}
            </Grid> */}
        </>
    );
};
