// apps/web/app/components/Video/index.tsx
/* eslint-disable jsx-a11y/media-has-caption */
import React, { useEffect, useRef } from "react";

type Props = {
    stream?: MediaStream;
};

export const Video: React.FC<Props> = ({ stream }) => {
    const videoRef = useRef<HTMLVideoElement>(null);

    useEffect(() => {
        if (videoRef.current && stream) {
            videoRef.current.srcObject = stream;
        }
    }, [stream]);

    return (
        <video
            style={{ position: "absolute", left: 0, top: 0, height: "100%", width: "100%" }}
            ref={videoRef}
            autoPlay
            playsInline
        />
    );
};

// apps/web/src/lib/components/Video/Video.svelte
<script lang="ts">
    import { getCallStore } from "$lib/store/local/call.svelte";

    const { peerId }: { peerId: string } = $props();

    let videoRef: HTMLVideoElement | undefined = $state();
    const callStore = getCallStore();

    $effect(() => {
        if (videoRef && callStore.peerConnection.otherStreams[peerId]) {
            videoRef.srcObject = callStore.peerConnection.otherStreams[peerId];
        }
    });
</script>

<!-- svelte-ignore a11y-media-has-caption -->
<video bind:this={videoRef} autoPlay playsInline>THEIR VIDEO</video>
